### PR TITLE
Rustfmt and changed edition to 2018

### PR DESCRIPTION
**Pull request by PerfectLaugh**
Edition is 2018 also

### CODE REVIEW

**Comment by quininer** [comment]
Can you look at this PR? @yoshuawuyts

**Comment by yoshuawuyts** [comment]
@quininer o/ thanks for the ping.

It seems there are quite a few things included in this PR; given I'm also somewhat new to the codebase I would appreciate it if we could perhaps split it out into a few smaller PRs, which would help with review.

What I'm thinking is:
1. make a patch to `cargo fmt`
2. write a patch to switch over to the new edition
3. introduce the new vectored API

Perhaps 1 + 2 can be merged. But as it stands this PR in itself has too many changes to confidently review right now.

**Comment by imor** [comment]
@yoshuawuyts I've opened PR #27 that just formats code using `cargo fmt`. If you can merge that and then maybe @PerfectLaugh can rebase on master again?

**Comment by PerfectLaugh** [comment]
I decided to just cleanup the code base. Rather than adding api without testing.

**Comment by imor** [comment]
@PerfectLaugh actually @yoshuawuyts wanted to split this PR into multiple sizable chunks so that it becomes easier to review, but with this a single commit it is exactly the opposite.

**Comment by PerfectLaugh** [comment]
> @PerfectLaugh actually @yoshuawuyts wanted to split this PR into multiple sizable chunks so that it becomes easier to review, but with this a single commit it is exactly the opposite.

I think the commit itself is not that important to split out the changes.
I only rustfmt and change the repo url, then resolve all the resolution failure in 2018 edition. Basically have no change on functionalities and apis.
I wonder if it is necessary. If so, I will make another commits satisfying your requirements.

**Comment by yoshuawuyts** [comment]
I've merged the three other PRs. I think opening a standalone PR for a vectored API should now be possible!

**Pull request closed without merging**
