### PR TITLE
Update to `miow` to use `windows-sys` 0.33

### PR DESCRIPTION
**Pull request by kennykerr**
This brings `miow` in line with the [parking_lot](https://github.com/Amanieu/parking_lot/blob/master/core/Cargo.toml#L26) and [winit](https://github.com/rust-windowing/winit/blob/master/Cargo.toml#L61) crates that have already adopted `windows-sys` version 0.33.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Note that this PR would be a breaking change, as we're re-exporting types from `windows-rs` in our public API. This would mean `mio` would need to upgrade their version of `miow` each time we update `windows-rs`. That's not a great situation to be in.

Ideally we could evade that by defining our own wrapper with an `#[repr(transparent)]` that can be converted to either one of `windows-rs` or `winapi` types. But I'd like to have that in place before we update `windows-rs` (having it as this PR would be fine too) so that we can limit the number of breaking changes we have to issue.

**Comment by yoshuawuyts** [comment]
(talked privately; we're going to include the required changes as part of this PR)

**Comment by faern** [comment]
`parking_lot` just merged an upgrade to `windows-sys 0.34`. https://github.com/Amanieu/parking_lot/pull/331. So if the intention is to try to use the same version this PR also needs to update to that.

**Comment by kennykerr** [comment]
Feel free to reopen the PR if you'd like to push this forward.

**Pull request closed without merging**
